version: '3'
services:
  nginx:
    image: nginx__image
    container_name: nginx
    build:
      context: .
      dockerfile: ./Dockerfile_nginx

    volumes:
      - /opt/src/sample:/var/www/public

    ports:
      - 80:80

    tty: true
    depends_on:
      - php

  php:
    image: php__image
    container_name: php
    build:
      context: .
      dockerfile: ./Dockerfile_php

    expose:
      - 9000

    volumes:
      - /opt/src/sample:/var/www/public

    tty: true
    depends_on:
      - db

  datastore:
    image: busybox
    volumes:
        - /opt/datastore:/var/lib/mysql
    command: [/bin/sh]

  db:
    image: mysql:5.6
    container_name: mysql
    ports:
      - '3306:3306'
    volumes_from:
      - datastore
    environment:
      MYSQL_DATABASE: bbs
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - "1000:80"
    volumes:
      - ./docker/phpmyadmin/sessions:/sessions

