version: '3'
services:
  php:
    image: php__image
    container_name: kb-php
    build:
      context: .
      # dockerfile: ./Dockerfile_php
      dockerfile: ./docker/Dockerfile_php

    ports:
      # - 80:9000
      - 9000:9000

    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=bbs
      - DB_USERNAME=root
      - DB_PASSWORD=root

    volumes:
      # - /opt/src/sample:/var/www/public
      - ./bbs:/var/www/public

    tty: true
    depends_on:
      - db

  datastore:
    image: busybox
    volumes:
        - /opt/datastore:/var/lib/mysql
    command: [/bin/sh]

  db:
    image: mysql:5.6
    container_name: kb-mysql
    ports:
      - '3306:3306'
    volumes_from:
      - datastore
    environment:
      MYSQL_DATABASE: bbs
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: kb-phpmyadmin
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - "1000:80"
    volumes:
      - ./docker/phpmyadmin/sessions:/sessions

